<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>dummy_bt_nodes</name>
  <version>0.0.0</version>
  <description>Generic dummy BehaviorTree nodes for high-level testing of the planning and execution model. Nodes only log their actions and fail only when required input ports are missing.</description>
  <maintainer email="rodrigo.perez@urjc.es">roi</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>behaviortree_cpp</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
